server:
    port: 8090
spring:
    cloud:
        config:
            #label: master
            name: config-server
            server:
                git:
                    uri: https://github.com/kaushal8707/cloud-config-props
